bash wrapper error handling

diff --git a/cron/templates/default/bash_wrapper.erb b/cron/templates/default/bash_wrapper.erb
--- a/cron/templates/default/bash_wrapper.erb
+++ b/cron/templates/default/bash_wrapper.erb
@@ -1,4 +1,14 @@
 #!/bin/bash
 PERL_SCRIPT="$1"
 PATH_TO_SCRIPTS="/srv/www/perlcsripts/current/"
-/opt/perlbrew/perls/perl-5.8.8/bin/perl $PATH_TO_SCRIPTS$PERL_SCRIPT
+source /etc/profile.d/perlbrew.sh
+
+perl $PATH_TO_SCRIPTS$PERL_SCRIPT
+
+if [ $? -eq 0 ]; then
+    echo OK
+else
+    echo "FAILED $PERL_SCRIPT" | mailx -s "Subject" a.panov@gmail.com
+fi
+
+
